### ISSUE TITLE
yticks misaligned

### ISSUE THREAD

**Issue by greimel** [JuliaPlots/MakieTeX.jl#31] opened 2022-05-22 20:20 UTC
Thanks for your great work on this package @asinghvi17 !

I've just played with the new release and I realized the following.

<img width="678" alt="image" src="https://user-images.githubusercontent.com/6280307/169714040-031afdfe-b075-4e1c-98e4-35cdaa0466a7.png">

```julia
begin
	MakieTeX.CURRENT_TEX_ENGINE[] = `tectonic`
	
	fig = Figure()
	ax = Axis(fig[1,1], 
		ytickformat = x -> latexstring.(string.(x))
	)

	v = 0.05:0.1:0.95
	#v = 0.19:0.1:0.99
	scatter!(ax, v, v)
	
	fig
end
```

Relatedly, when you are unlucky, the ticks look like this (reproduce by uncommenting line 10 above)

<img width="683" alt="image" src="https://user-images.githubusercontent.com/6280307/169714112-06ec0fd9-d7ee-4e06-add3-a0af9e006474.png">

It would be nice if the example code in the readme were more robust. Probably one can call some internal function in Makie that produces the nice strings from tick values.

**Comment by asinghvi17** [comment] 2022-05-22 20:37
Huh!  Can reproduce the issue in CairoMakie as well.

Looks like my left/right align code is off.  Will try to fix that soonish.

**Comment by asinghvi17** [comment] 2022-05-22 20:47
With some quick adjustments, the figure now looks like this.
![iTerm2 tYf3TV](https://user-images.githubusercontent.com/32143268/169715013-b3aa5487-b39b-4fde-898c-05685989d3ee.png)

AFAICT the labels are cut off to the left because of the Axis protrusion calculation...I'll have to look further into that to see how to avoid this.  Could be an error in the boundingbox calculation for multiple tex images.

**Comment by asinghvi17** [comment] 2022-05-22 23:13
Aha!  Found the problem - the plot coming from Axis is of type `MakieCore.Text{Tuple{Vector{Tuple{AbstractString, Point{2, Float32}}}}}`, while we only dispatch on Texts which contain Vectors of CachedTeX!  I fixed that and pushed a branch which should auto-close this issue when merged.

Thanks for the tests and putting up with my not seeing these error cases, @greimel!

**Closed** 2022-05-23 00:16 UTC
